### ISSUE TITLE
getElectionStatusMethods

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#105]
- [ ] Create an object of the methods that get election status. The object will be used in electionMethods.  Extracting the methods out of navigation-panel.js

The interface/pattern to be compatible with useMethods (see below)

app/lib/get-election-status-methods.js
```JS

// pure functions should be declared outside the object
const checkDateCompleted = obj => {
        // eslint-disable-next-line no-restricted-syntax
        for (const key in obj) {
            if (obj[key].date !== '') {
                return true
            }
        }
        return false
    }

// state is the electionObj
// dispatch would be called by a method that wanted to change the state
const getElectionStatusMethods=(dispatch, state)=>({
        checkDateCompleted: checkDateCompleted,
        checkTimelineCompleted: ()=>{
            return (
            checkDateCompleted(state?.timeline?.moderatorDeadlineReminderEmails) &&
            checkDateCompleted(state?.timeline?.moderatorSubmissionDeadline) &&
            checkDateCompleted(state?.timeline?.candidateDeadlineReminderEmails) &&
            checkDateCompleted(state?.timeline?.candidateSubmissionDeadline)
            )
        },
        ....
})

export default getElectionStatusMethods
```

- [ ] import and expand this object into .storybook/preview.js 

```JS
import getElectionStatusMethods from ../app/lib/get-election-status-methods

const electionOM = useMethods(
            (dispatch, state) => ({
                ...getElectionStatusMethods(dispatch, state),
                upsert(obj) {
                    dispatch(merge({}, state, obj, { _count: state._count + 1 }))
                },
                ...
```

- [ ] Do a couple status methods and make sure it works before doing the whole thing to make sure this pattern for pulling the methods into useMethods actually works.

- [ ] Then update navigation-panel to use the methods out of electionMethods.

- [ ] create jest tests for each method in:

app/lib/__tests__/get-election-status-methods-[method-name].js
where [method-name] is one of the methods in the file
see [cloudinary-urls.test.js](https://github.com/EnCiv/undebate/blob/civ-serv/app/components/lib/__tests__/cloudinary-urls.test.js) for an example of writing a test. 
see [Testing](https://github.com/EnCiv/undebate-ssp#testing) for more on tests

- [ ]  for now lets just do 1 or 2 tests for each method. We want to make this component available soon and I see this tests as something we will have to keep updating and adding to as we encounter different situations.

**Comment by kamui-fin** [comment]
How do you interface with the status methods from a jest test? Since it's a react hook (useMethods), it isn't callable inside of a normal unit test.

**Comment by ddfridley** [comment]
@kamui-fin a fair point.  useMethods takes a function, which returns an object that has all the functions as properties.   Perhaps the jest test should call that function, passing it's own dispatch function and state. And then test the functions.  Or the functions could be exported from where they are and imported by the jest test.
