### ISSUE TITLE
UndebatesFooter

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#110]
```
<UndebatesFooter
className={}
style={}
>
```

- [x] The component should layout differently depending on the orientation.  It might be useful to use the orientation media query.  
- [x] besides what you see here, in the bottom left corner we need a link to the terms of service.  See app/components/footer
- [x] And in the middle of the bottom line it should say Copyright (c) 2022 EnCiv, Inc
- [x] Donate button should open a new tab with this:  "https://www.paypal.com/donate/?token=0jSAROyRh4xb0aOJyweWalSJZ56axU9FYYwTrxtoUI1g0qg_ciUviTYmlu4jGsHW3lCFd0&country.x=US&locale.x=US",
](https://www.paypal.com/donate?token=0Z4RhCNTrQZOySdxjW7WJHVBfQgJ8x2QKef78w342CAGyYyO9dM26XmswH3lMhkiPM5-yJ3dlXWiY67l

- [x] Landscape Layout

[![image](https://user-images.githubusercontent.com/3317487/154754074-df3f8927-936f-4fc0-b7cf-f0d781b70c29.png)](https://www.figma.com/file/yXrcMvg5EIwdLkHHxIdILh/Undebate-Self-Service-Portal?node-id=2268%3A3831)

- [x] Portrait (smartphone) Layout

[![image](https://user-images.githubusercontent.com/3317487/154754332-6f6caebc-0d8a-412e-97d5-39b3bd0e88a0.png)](https://www.figma.com/file/yXrcMvg5EIwdLkHHxIdILh/Undebate-Self-Service-Portal?node-id=2268%3A5847)

**Comment by ddfridley** [comment]
@Gluay88 Here's a little bit of code from [unpoll.js](https://github.com/EnCiv/unpoll/blob/main/app/web-components/unpoll.js) that shows how to do different orientations.
```JS
const useStyles = createUseStyles({
  unpollViewPort: {
    width: `calc(100vw - ${storybookPadding})`,
    minHeight: `calc(100vh - ${storybookPadding})`,
  },
  unpollWrapper: {
    width: '48em',
    marginLeft: 'auto',
    marginRight: 'auto',
    textAlign: 'center',
    padding: 0,
    backgroundColor: 'black',
    //minHeight: `calc(100vh - ${storybookPadding})`,
  },
  '@media (orientation: portrait)': {
    unpollWrapper: {
      width: '100%',
    },
  },
})
```

**Comment by Gluay88** [comment]
Thank you David.
