### ISSUE TITLE
LandingTimeline Component

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#111]
```
<LandingTimeline
    className={}
    style={}
 />
```
- [ ] Depending on the orientation of the display, the timeline should render in Landscape or portrait
- [ ] Most of these icons are already in app/svgr, check there before creating new ones

Landscape: 
[![image](https://user-images.githubusercontent.com/3317487/154759881-1b0673ea-a091-4dff-b430-6397bd3ec745.png)](https://www.figma.com/file/yXrcMvg5EIwdLkHHxIdILh/Undebate-Self-Service-Portal?node-id=2011%3A3768)

Portrait:
[![image](https://user-images.githubusercontent.com/3317487/154760056-36d7b102-bbdb-4701-948d-c8193d3f16e3.png)](https://www.figma.com/file/yXrcMvg5EIwdLkHHxIdILh/Undebate-Self-Service-Portal?node-id=2268%3A6148)

**Comment by BolunThompson** [comment]
I'll take this issue

**Comment by ddfridley** [comment]
@BolunThompson Great. I assigned it to you.  While you are working on this one, please also think about #19.  The difference is this one is static, just for the landing page. Where as the other one should take it's data from electionObj, and is more interactive.

**Comment by ddfridley** [comment]
Closed by #132
