### ISSUE TITLE
TimeLinePoint

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#12]
```
<TimeLinePoint
  className={}
  style={}
  title=""
  description=""
  dateTimes=[] // list of date/time pairs. 
  onDone={()=>{valid: bool, value: any}}
  ref={} // parent will use ref to get height so it can determine where to put the circles
/>
```

- [ ] If a date/time is initialized and in the past, it should not be editable.
- [ ] The white bubble does not need to be rendered by this component - it will be done by a parent component

Requires:
- #6 
- #7

![image](https://user-images.githubusercontent.com/3317487/129128292-13c34520-9c98-4d5a-b573-b81267b8871e.png)

**Comment by ddfridley** [comment]
@alex-808 I made updates to this issue description. I don't know if you get notified when I do - so here it is.

**Comment by ddfridley** [comment]
@alex-808 are you going to work on this? If not - please unassign yourself. It's okay if you want to work on other issues - but maybe you forgot.  I haven't been reviewing status with people.

**Comment by alex-808** [comment]
@ddfridley I'm working on it now although I did forget about it, sorry about that. I plan on having a PR for it by the end of the day. I have a good amount done already.
