### ISSUE TITLE
Convert other stories to the makeChapter pattern

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#140]
See [stories/election-header.stories.js](https://github.com/EnCiv/undebate-ssp/blob/main/stories/election-header.stories.js) for the makeChapter pattern.  

Convert other stories to this pattern.

Are there stories where this pattern and the one makeChapter file don't fit? - Lets discuss.

**Comment by nicholas-terry** [comment]
Handle comment

**Comment by ddfridley** [comment]
Enough stories have been changed to the pattern, we don't need to change them all.
