### ISSUE TITLE
NavState Component

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#145]
Create a component to manage the state, and provide actions for the Home button and the Back button.

One way to do this is described below.  Another way to do it would be to use ReactRouter.  It's up to you.

[![image](https://user-images.githubusercontent.com/3317487/129801762-713be3a7-e26d-48ca-9c3e-da6421d29b6f.png)](https://www.figma.com/file/IQKPx02pkBErpmhQoECoq9/Undebate?node-id=132%3A7175)

The Election Header Bar renders a \<BackButton/\> and a \<HomeButton\> currently these buttons just return an SVG.

- [x] Create a new component that wraps around the UndebateHomePage and provides a React Context 

```
<NavState {...props}>
    <UndebateHomePage >
</NavState>
```

- [x] NavState pass all it's props to it's child
Here is an example of how to pass props to a child: https://github.com/EnCiv/unpoll/blob/main/app/components/login-store.js

- [x] The context will provide:
navState.componentStack[] - an array where component names will be pushed and poped
navState.home() - clears the componentStack and causes a arerender
navState.back() - pops off the latest componentStack and throws it out, and causes a rerender
navState.push(component) - pushers the latest component name onto the stack

- [x] Modify the BackButton to import the context and call navState.back() when the user clicks on it

- [x] Modify the HomeButton to import the context and call navState.home() when the user clicks on it

- [x] Modify UndebateHomePage to import the context and render the last item in navState.componentStack[], and to NavState.push the 

- [x] new component name every time onDone is called with a new component name

- [x] Create a story for NavState 

See https://reactjs.org/docs/context.html for doing React Context.
NavState will probably have to be a class component because Context.Provider can only be a class.
But everything else should use React.useContext in functional components.

In my ideal, the nav-state.js file would export both the NavState React Class component, and the React.createContext value, but I can't tell you for sure if it can be done that way.

**Comment by ice1080** [comment]
Hey @ddfridley, most of the things in this issue are basically reinventing the wheel with things that React Router does for you. 
If the primary goal is navigation and context/history, are you ok if the usage of React Router leads to several of the checkboxes in the issue being slightly different in their implementation?
Additionally I'm not sure how exactly a story would work for this, but React Router is unit testable if that is sufficient?

**Comment by ddfridley** [comment]
Go for it! It would be a plus to be using react router in this project.
We may also need to create a dedicated /route for /undebates..... rather than using the iota path method. That's fine.  I'm all in. 
For a story, I wash thinking that the router implementation could be mocked to start with the story location - 
ie `/?path=/story/undebate-homepage--new-user` instead of `/undebates` but whatever works is great.

**Comment by ddfridley** [comment]
This has been done using react-server-dom and and it's useSearchParams hook.  The code is in #181
