### ISSUE TITLE
Various Defects/Issues

### ISSUE THREAD

**Issue by ice1080** [EnCiv/undebate-ssp#162]
This issue is being used to hold various issues noticed at any time in any part of the app or storybook. It can be added to at any time prior to the v1 release

- [x] Typo: "underbate" should be "undebate" (multiple instances of this)
- [x] Typo: "archieved" should be "archived" (multiple instances of this)
- [x] Datetime Input stories "Filled" and "Disabled" are the same as "Default"
- [x] Datetime Input stories "Default 2" and "With Default Value 2" have a display issue
- [x] Vertical Timeline story throws an error
- [x] Script Page stories "Default", "Locked", "Edit", "Error" all throw errors
- [x] Typo: "countSubmissionReminderSet" should be "countSubmissionReminderSent" (multiple instances of this)
- [x] "countSubmissionAccepted" and "countSubmissionDeclined" might make more sense as "countInvitationAccepted" and "countInvitationDeclined" since it's checking the invitations?
- [x] consider renaming "getSubmissionStatus" to "getModeratorSubmissionStatus" to be more descriptive
- [x] App story "Nothing Here" throws an error
- [ ] Fix failing unit tests

**Comment by ddfridley** [comment]
I fixed Vertical Timeline story - it was an issue with uninitialized data in time-point.js  It will be pushed in an upcoming PR.

**Comment by ice1080** [comment]
@ddfridley any preference on the method renames? I'm fine to leave it if you prefer or can do refactoring to rename methods to be more descriptive if preferred.
I'm specifically referring to these two:
- [ ] "countSubmissionAccepted" and "countSubmissionDeclined" might make more sense as "countInvitationAccepted" and "countInvitationDeclined" since it's checking the invitations?
- [ ] consider renaming "getSubmissionStatus" to "getModeratorSubmissionStatus" to be more descriptive

But I was also thinking of renaming multiple things where the only difference between moderator and candidate is singular vs plural.

**Comment by ddfridley** [comment]
It would be much easier to read if it was ...ModeratorSubmission and CandidateSubmissions. 

Another challenge:
If you look at app/components/done-locked-button * have created a button that the user has to click to say that they're done with that panel.  But I haven't factored that additional status info in to a lot of places.  Frankly, it's not immediately clear  where all the places are that it needs to be done.

I know several people have been contributing to this file.  Is there a way to do the naming to make it more apparent all the places that need a change if something new is added to a panel.  (I added some new fields like organizationUrl and organizationLogo).

I don't know a good way to do this.  maybe just fixing the names will be enough but I'd welcome your thoughts. 

Thanks,
david
