### ISSUE TITLE
footer too wide

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#167]
the footer is ending up slightly wider than the viewport, causing a horizontal scroll bar to be added to the page that otherwise should have one.

'app/components/footer.js'

it works correctly in storybook, but when you `npm run dev` and go to http://localhost:3011/home you get the problem.

- [x] The footer should not add width to the page it is at the bottom of.
- [x] The /home page should not end up with a horizontal scroll bar at the bottom

![image](https://user-images.githubusercontent.com/3317487/179848188-a8926896-84e1-48e1-83b4-0414d858cb8a.png)

**Comment by ice1080** [comment]
Looks like this one is actually caused because the div above it has a style of `width:100vw;height:100vh`. Looking into this to find out where it's coming from.
