### ISSUE TITLE
ElectionHeader

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#18]
```
<ElectionHeader
   defaultValue=0 // the initially selected index, usually 0
   elections=[] // an array of election data objects
   onDone() // calls onDone(i) with the index of the object the user selected
>
```
link to figma: https://www.figma.com/file/IQKPx02pkBErpmhQoECoq9/Undebate?node-id=132%3A7175
![image](https://user-images.githubusercontent.com/3317487/129801762-713be3a7-e26d-48ca-9c3e-da6421d29b6f.png)

**Comment by ddfridley** [comment]
@rodolfonei Update on how onDone works:  onDone should be called with `{valid: bool, value: any}` So in this case it should be `onDone({valid: true: value: i })` where i is the index of the object the user selected.

**Comment by rodolfonei** [comment]
@ddfridley Ok, got it!

**Comment by ddfridley** [comment]
elections=[{electionName: string},{electionName: string}]

**Comment by ddfridley** [comment]
![image](https://user-images.githubusercontent.com/3317487/142740743-c9016613-70f7-4c27-98cd-77b31827a8c9.png)

This is the header part of the figma.
