### ISSUE TITLE
Issues related to email

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#185]
- [x] Logo in the email needs a default if not provided by the admin
- [x] Add a new Contact Name field on the Election page and save to db
- [x] Emails from address is changed from "My Company" to be "<contact-name>@<organizationName> via EnCiv.org"

**Comment by ice1080** [comment]
@ddfridley do we have a default logo file already somewhere?

**Comment by ddfridley** [comment]
done in #208
