### ISSUE TITLE
Submission status incongruent

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#195]
In the nav panel, the submissions status is shown 0 0 0 1, but in the content panel its showing 0 2 1 3

![image](https://user-images.githubusercontent.com/3317487/191348622-0631e7f2-a5f7-4001-a79f-bfa9b3b3d3ab.png)

In the original idea of submissions there would be invitation accepted/declined and automatic reminders.  But we just haven't implented those yet.

- [ ] For now we should make the submission status (in the left that says 0 0 0 1) be congruent with what is displayed on the right.

- [ ] Skip the icons and just use the same oval with a number in it format. 

- [ ] If the cursor hovers over an oval, show the text name of it.

- [ ] If all candidates have submitted, then just show a purple check mark like all the other statuses

**Comment by ice1080** [comment]
@ddfridley will this change also affect the candidate status table in the undebates list component?
![image](https://user-images.githubusercontent.com/25037168/191639270-6052765e-e5b5-4d4f-9e43-0333067b8925.png)

**Comment by ddfridley** [comment]
Good point. Yes. It makes sense to be consistent.

**Comment by ice1080** [comment]
Just about have this one done, just have the purple checkbox left.
