### ISSUE TITLE
candidate line

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#25]
<CandidateLine
 candidateData={}
/>

Build component that shows the candidate line:
figma: https://www.figma.com/file/yXrcMvg5EIwdLkHHxIdILh/Undebate?node-id=390%3A5130
![image](https://user-images.githubusercontent.com/3317487/132443126-364a9f16-5701-4933-ba55-3b1c097906d4.png)

**Comment by gmunilla14** [comment]
Good Issue!

**Comment by ddfridley** [comment]
closed by #37
