### ISSUE TITLE
Script component

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#49]
```
<Script
    className={}
    style={}
    onDone={()=>({valid: bool, value: {script: []})}
    electionOM={[electionObj, electionMethods]}
>
```
see #46 for electionOM details.
```
    electionObj={..., script: [], questions: [] ...}
```
- [ ] If there are no questions yet, just render an empty page
- [ ] The length of the script array, should be one more than the length of the questions array.  
- [ ] The text above each script item should be auto generated based on the number of questions.
- [ ] The text of the last script item should always be what you see in the last item here. 
- [ ] The text of each script item should be auto populated from a template that we can easily tweak, and it should include the text of the question.  There will be a standard template for the first item, a standard template for middle items, and one for the last item.
- [ ] When this component rerenders the questions array needs to be checked, and the script updated accordingly.  
- [ ] Consider that the text of a question may change
- [ ] Consider that a question may get deleted in the middle

Requires:
- #14 
- #10

figma: https://www.figma.com/file/yXrcMvg5EIwdLkHHxIdILh/Undebate-Self-Service-Portal?node-id=344%3A5187

- [ ] see designer's comments to the right of the figma drawing of the component

![image](https://user-images.githubusercontent.com/3317487/143967532-1c95deb7-a95b-4266-95c8-441752c84f8c.png)

**Comment by BolunThompson** [comment]
Hello! I can work on this issue. To clarify, why should the script array be one larger than the question array? Shouldn't they be the same length?

**Comment by ddfridley** [comment]
@BolunThompson The script array should be one larger, because after the moderator asks the questions, the moderator gets to say thank you to the audience. So the moderator gets the first word, and the last word.
