### ISSUE TITLE
Election Category Component

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#5]
The Election Category Component will render the info on the left panel of the screen - 
https://www.figma.com/proto/IQKPx02pkBErpmhQoECoq9/Undebate?node-id=132%3A7175&scaling=min-zoom&page-id=102%3A2&starting-point-node-id=132%3A7175&show-proto-sidebar=1

```
<ElectionCategory
  categoryName= eg Election, Timeline, Questions, DangerZone, ...
  status=["Done", "Done and Locked", "Pending", "Invite Accepted", "Sent", "Reminder Sent", "Invite Declined", "Deadline Missed", "In Progress"
  numCandidatesRecorded=18
  numCandidates=34
  daysLeft=19
/>
```
When the status is In Progress, show the progress bar at the bottom, showing the ration of numCandidatesRecorder to numCandidates

A parent component will decide which ElectionCategory is selected, and change it's background color

Here's the link to the figma
https://www.figma.com/file/yXrcMvg5EIwdLkHHxIdILh/Undebate?node-id=337%3A4104

![image](https://user-images.githubusercontent.com/67896359/131639227-a3def439-0f05-4c85-852c-2ecc66176b72.png)

**Comment by BolunThompson** [comment]
I can work on this.

**Comment by ddfridley** [comment]
In the figma for the UI I see a lot of cases and icons and thing. I am going to propose a change to the component interface spec to make it more generic: 
```
<ElectionCategory
  categoryName= eg Election, Timeline, Questions, DangerZone, ...
 statusObjs=[{"completed": true}, {"pending": true,}, {"daysLeft": 9}, ...]
/>
```
If statusObjs is empty - that's "default" in the UI descirption.
If a statusObj key matches a known key (like completed), then display the associated icon. (if value is false don't display the icon)
If a statusObj has a meaningful value, like daysLeft - then the value is also displayed
There can be multiple statusObj's, render them all.
Looking at the last example "Submissions" it would be:
statusObjs=[{accepted 29}, {declined: 2}, {reminderSend: 2}, {deadlineMissed: 1}]
What's displayed will depend on the value - if the value it true, only the Icon is shown.  If the values is a number, show the Icon with the number. 
So, numCandidatesRecorded and numCandidates would get turned into:
{"percentComplete":  90}
If there is a key/value that does not match anything know, show the humanizeString of the key, and if the key is a number or a string, show that.  

It will be the work of the parent element to convert it's content into statusObjs.
