### ISSUE TITLE
UploadCSV component

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#54]
```
<UploadCSV
    className={}
    style={}
    electionOM={[electionObj,electionMethods]}
>
```
See #46 for electionOM details

- [x] It should be **CSV** not cvs in the name
- [x] Initially the component renders the button
- [x] When someone clicks on the button, then it also renders the popup (as well as the button)
- [x] After the file is uploaded, it is extracted into an object, and the column names are checked. 
- [x] If the column names match, and the electionObj.electionTable is empty, add the rows to the table. And, if there is not already a uniqueId column, create one and initialize each row it's own `objectid().toString()`  from 'isomorphic-mongo-objectid'
- [x] If there is already electionObj.electionTable - then you will have to merge the new data into the existing data.
- [x] first if there is a uniqueId column in the incoming data, use that to merge the new row with the existing row
- [x] second - if no uniqueId column in the incoming data, use the email address to merge
- [x] or third - if no uniqueId and no email match, use the Candidate Name and Office to find a matching row and merge.  - this is the case when the email address is changed.
- [x] then add new data to the table - make sure each new column gets a uniqueId
- [x] finally call electionMethods.updateElectionTable(row, objs) with the list of new/updated rows
- [x] If there is an error, render specific,  helpful information to the bottom of the popup.   Allow the user to upload again, or cancel. 
- [x] - [ ] When it says add the data to the table, above - that's a local, working copy of the table.  The call to updateElectionTable will update the real data and cause a rerender of the component that will display it.

figma: https://www.figma.com/file/yXrcMvg5EIwdLkHHxIdILh/Undebate-Self-Service-Portal?node-id=368%3A5037

![image](https://user-images.githubusercontent.com/3317487/144514058-1c1820a0-c0ca-4c15-8fe9-c8c5338fbb3d.png)
![image](https://user-images.githubusercontent.com/3317487/144527125-43458aec-563e-4b2e-a4e4-b6c17f4aeee5.png)

**Comment by ddfridley** [comment]
@ice1080 
Great questions.  I am copying this discussion from slack to git so that it can be seen by others, and stored with the issues that we are discussing. 
> 1. What functionality are we expecting for the Check Sample link. Does this take the user to a certain page, or download a sample csv text file?

Downloads a sample csv file.

> 2. What styling are we looking for around the drag and drop box in the popup? Do we want some highlighting, similar to something like this? https://sarink.github.io/react-file-drop/
 a. Also what should it say a file is selected?
 b. I'm happy to make decisions around all this, just wasn't sure if we already had this defined somewhere or if you prefer to make these decisions.

Not sure what you are referring to the styling at react-file-drop but maybe you mean that it reacts when you drag the file over, and stuff and I'm all for it.  Also great to use MIT and ISC licensed components from npm.

Probably best to discuss this with the group on Tuesday. UI decisions need lots of different perspectives, but I there are probably some implementation details that aren't covered in the UI that you can decide on - and then show. 

> 3. Is there a way for storybook to exercise button clicks, and/or files being selected? I know there are addons, I was just curious if I should be writing stories that show the popup visible, as well as stories that have pre-built files selected.

Exercise buttons yes, select the files not sure.  But - they have made major changes to Storybook since I last worked with exercising buttons, so you would have to figure it out. And I would be very grateful if you did.

Some stories need  human interaction to see that they are working.  That's ok for now.  Storybook have been a great way to build components independently and test them.  Also see the last sentence of this comment about the stage we are in. 

> a. I could also build separate stories for the popup on its own and import that into the UploadCSV component

Up to you. Some people have created additional stories and components. That's great.

> 4. I noticed we have a dependency on enzyme but we don't use it anywhere. Since this is a more complex component than some because of the popup and the file upload, would it be best to write some actual unit tests that more fully test the functionality of all the cases mentioned in the issue?

If you figured out clicking in storybook that would be the most valuable.  If you wanted to go for broke. its also possible to use storybook with jest (and maybe enzyme or maybe they have something else) to run the storybook tests.  But again, it was several major version of Storybook ago that I did that.  

But at this stage we are not looking for really thorough testing  - we are racing to get something running and in front of users so we can get feedback (because no one ever designs it perfectly the first time), and prove we have a market.

**Comment by ice1080** [comment]
Thanks for following up @ddfridley!
I'll work on the sample file for 1). 

I see that react-file-drop is MIT licensed, so we should be good with that and I will demo what I have on Tuesday for 2).

I see that the @storybook/addon-interactions package allows the storybook tests and automated interactions such as clicking and possibly file uploads as well, not sure yet on that. That answers 3) for me. 

Based on the info for question 3), if I get that working then that should be sufficient for testing for 4). If not I'll use enzyme. I feel like several of the other components are setup in a way that allows most of their cases to be tested via storybook, but the file drag/drop or file selection is what makes this one unique. I want to ensure that it works for various cases both now and if there are future changes, so hopefully storybook interactions should cover all that. I also feel like it shouldn't take long to add those cases, so it shouldn't slow down overall work on this.

**Comment by ice1080** [comment]
As I am working through the final case of matching rows for this component (matching on name and office), I thought about a case that might not produce desired behavior in an edge case. 
Let's say we have two John Smiths running for the same office. If one of them were to change their email and we were importing the csv to do this change, then this will produce indeterminate behavior; it may or may not update the correct row. I'm guessing that we would never hit this condition, but did want to mention it in the issue.

**Comment by ddfridley** [comment]
Understood. We might want to reject or something if there are two candidates either exactly the same name. Or we could create an issue for it and deal with it later. It's rare but not impossible. But the election in general will gave a problem with that too.

Thanks


⁣Get BlueMail for Android ​

**Comment by ddfridley** [comment]
Great.
Put sample.csv in assets/csv (new directory), and we can update it as we need to. Then you can link to it at /assets/csv/sample.csv

And as I think about it, lets call it sample-candidate-table.csv to make the name more descriptive.

**Comment by ddfridley** [comment]
done #135
