### ISSUE TITLE
undebate component

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#57]
```
<Undebate
    className={}
    style={}
    electionOM={[electionObj, electionMethods]}
>

const {undebate, ...}=electionObj
const {url, ...}=undebate  // url of the undebate
```
see #46 for description of electionOM

- [x] create QR code using url
- [x] [qrcode.react](https://www.npmjs.com/package/qrcode.react) looks like a good option but open to others.

figma: https://www.figma.com/file/yXrcMvg5EIwdLkHHxIdILh/Undebate-Self-Service-Portal?node-id=541%3A3978
![image](https://user-images.githubusercontent.com/3317487/144725415-8f15f697-7238-48cb-94cd-f2ae06c48838.png)

**Comment by kamui-fin** [comment]
When the download button is pressed, will the browser start a download for the image file of the QR Code itself? If so, will SVG work?

**Comment by ddfridley** [comment]
I think the QR Code will need to be a PNG for most editors to work with.
