### ISSUE TITLE
ESLint

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#67]
- [x] Add eslint to this project, working with the team on best practices.  
- [x] Change files names from \*.jsx => \*.js,  \*_\*=> \*-\*
- [ ] Fixup all the files so that lint passes.  
- [x] Add description to README.md about how to setup eslint on visual studio code

**Comment by alex-808** [comment]
One thing I thought of which might be something worth '--fix'ing might be exports. So far we've been using default exports which might be a good thing to enforce more rigidly as confusion using named/default exports could cause some issues for people down the road if it's ambiguous.
