### ISSUE TITLE
API send-moderator-invite

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#78]
## Client 
socket.emit('send-moderator-invite', id, cb)

## Server
app/socket-api/send-moderator-invite.js
function sendModeratorInvite(id,cb){
}

We will use [Send In Blue](https://developers.sendinblue.com/docs/send-a-transactional-email), and the npm packate [sib-api-v3-sdk](https://www.npmjs.com/package/sib-api-v3-sdk)

- [x] if user is not logged in, cb() and logger.error
- [x] use id to get the election record
- [x] See this example of using SendInBlue to send emails: https://github.com/EnCiv/undebate/blob/master/app/server/events/notify-of-new-participant.js
- [x] Create your own free Send In Blue account for testing.
- [x] Send In Blue uses templates. You will have to create a model template to use for this.  The id of the template shall be stored in an env variable. 
- [x] The election name, moderator name, greeting, and script will be sent to sendinblue as data to be used in the message. There will likely be other.
- [x] Upon sending the email, a database entry will be generated. The parentId will be the election. It will include template id, and all the data sent to send in blue. It will have webComponent.webComponent: "ModeratorEmailSent"
- [x] Put the _id of the database entry in the `tags` field when sending the message so that in the future we can track the status of it.
- [x] Keep the SendInBlue specific stuff in a separate module, we will use it again when we send candidate emails.

**Comment by nynaalekhya** [comment]
Hi @ddfridley
I have been working on this issue

**Comment by ddfridley** [comment]
@nynaalekhya How's it going? I haven't head from you in a while, We are getting close to the end and I am jumping in on this task.
