### ISSUE TITLE
ElectionTextInput

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#9]
```
<ElectionTextInput
   name="Email Address"
   defaultValue=""
   checkIsEmail=true
>
```

![image](https://user-images.githubusercontent.com/3317487/128968593-1ac51b44-41b5-405f-9f94-2bac198efc49.png)

**Comment by ddfridley** [comment]
@alex-808 I just realized something.  In the story there is a form, and a submit button.  Since this is a web app, we won't be using a from (which would post the data to the server). Instead when the user completes the input, perhaps by hitting <CR> or <Tab> or clicking outside of the box (onBlur) then the data is passed to the parent component through a callback like onChange.  This input component was passed onChange and onDone the first was for the changes and the latter indicated that it was done and valid.  [unpoll's inpute-element](https://github.com/EnCiv/unpoll/blob/main/app/components/input-element.js )  I didn't specify what to do in this issue - so you can call this feature creep but have you seen any patterns for passing the data up? I would love to discuss it.  Or, if you don't have any better ideas can you follow the onChange / onDone patter for now.  But I'm wishing for a common practice way to do it with just one callback instead of two.  -- And if this sounds crazy lets talk. Thanks - david.

**Comment by alex-808** [comment]
@ddfridley I think I'm following but let me make sure I understand:

There will be only two events which should trigger validation and passing up the data to the parent: 1. onBlur 2. 'enter' keypress.

If this is the case then the onChange callback could remain as it is, only updating the local state of the component and would not need to be passed as a prop. But we could just pass the one onDone callback as a prop down from the parent which would be triggered by the above events. onDone could make sure the data was valid and pass the data up to the parent.

Does this idea work or does a parent container also need to be aware of changes before onBlur or an 'enter' keypress? I was thinking that if either of these events haven't occurred yet, the parent doesn't need to be passed the state and so changes to text can just remain in local component state. Let me know if I am missing something. Thanks

**Comment by ddfridley** [comment]
@alex-808 great analysis.  The parent does not need to know about the changes, it only needs to receive the data when it is done.  But it also needs to be informed if the data goes from done to not done.  Like if the person entered a valid email address and then edited it and made it invalid (or blank).  one idea would be for onDone to return {valid: bool, value: any} . onDone would return {valid: false} In the case of the field going blank or something.  In the case of unpoll, the parent only allows the page to advance when everything on the page is done.  Usually you would just say a field is required- but I've seen that it needs to be left to higher level logic do decide if things are required and when - it's not always binary.

So if it makes sense to you we could use only onDone and have it return {valid: bool, value: any}.  And we can try it this way in this project.  (unpoll will remain the same unless we decide to refactor).  But how does this pattern sound to you?

thx

**Comment by alex-808** [comment]
Sounds good! I'll implement it and be back with another PR.
