### ISSUE TITLE
auto size the columns, up to the full width in candidate-table-input

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/undebate-ssp#92]
app/components/candidate-table-input.js
app/components/submissions.js

and see https://react-table.tanstack.com/docs/examples/full-width-resizable-table

**Comment by nynaalekhya** [comment]
Hi @ddfridley 
I'm working on this issue

**Comment by raeplusplus** [comment]
I can take this issue

**Comment by ddfridley** [comment]
Great! Please ask if you need an explanation of anything. I know it's hard to get started in other people's code.

**Comment by ice1080** [comment]
Hey @ddfridley do you want the cells to have a minimum width of what they currently are?

**Comment by ddfridley** [comment]
Up to you. We will run into situations where the view port is  smaller, and at some point the table may need to be wider than the viewport.

**Comment by ice1080** [comment]
I set the minWidth of the input to 10rem for now, feel free to update it to whatever. This seemed to only be needed for candidate-table-input.js, as submissions.js was already auto sizing.
